media:
  input: assets/images
  output: /assets/images

content:
  - name: pages
    label: Pages
    path: _pages              # points to where your files actually are
    type: collection
    view:
      title: title
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: layout
        label: Layout
        type: string
        default: page
        hidden: true
      - name: permalink
        label: URL Path
        type: string
        description: 'The URL for this page (e.g., /contact/ or /biotechnology/)'
      - name: body
        label: Body
        type: rich-text
